### ISSUE TITLE
amplify init error: "InvalidClientTokenId: The security token included in the request is invalid" 

### ISSUE THREAD

**Issue by boctor** [aws-samples/amplify-photo-gallery-workshop#3]
Following the directions here: https://amplify-workshop.go-aws.com/30_adding_auth/10_adding_auth_back.html

resulted in this error:
```
workshop:~/environment/photo-albums (master) $ amplify init
Note: It is recommended to run this command from the root of your app directory
? Choose your default editor: None
? Choose the type of app that you're building javascript
Please tell us about your project
? What javascript framework are you using react
? Source Directory Path:  src
? Distribution Directory Path: build
? Build Command:  npm run-script build
? Start Command: npm run-script start
Using default provider awscloudformation

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-multiple-profiles.html

? Do you want to use an AWS profile? Yes
? Please choose the profile you want to use default
⠋ Initializing project in the cloud...An error occurred when creating the CloudFormation stack
✖ Root stack creation failed
init failed
{ InvalidClientTokenId: The security token included in the request is invalid.
    at Request.extractError (/home/ec2-user/.nvm/versions/node/v8.10.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/home/ec2-user/.nvm/versions/node/v8.10.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/ec2-user/.nvm/versions/node/v8.10.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/ec2-user/.nvm/versions/node/v8.10.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/home/ec2-user/.nvm/versions/node/v8.10.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/ec2-user/.nvm/versions/node/v8.10.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/ec2-user/.nvm/versions/node/v8.10.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/ec2-user/.nvm/versions/node/v8.10.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/ec2-user/.nvm/versions/node/v8.10.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/home/ec2-user/.nvm/versions/node/v8.10.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
  message: 'The security token included in the request is invalid.',
  code: 'InvalidClientTokenId',
  time: 2019-01-15T22:10:48.503Z,
  requestId: '69acab04-1912-11e9-9782-c9d2308561c2',
  statusCode: 403,
  retryable: false,
  retryDelay: 88.90341735319167 }
An error occurred when  creating the CloudFormation stack
```

**Comment by boctor** [comment]
I resolved it by:
* Logging back in as the root account user, editing the `workshop` IAM user by opening the "Security Credentials" tab, tapping "Create Access Key" and saving the csv.
* Back in Cloud9, selecting "AWS Cloud9" then "Preferences" and under "AWS Settings" turning off "AWS managed temporary credentials"
* On the Cloud9 console, I then ran `amplify configure` and manually entered the Access Key ID and Secret access key from the saved csv.

**Comment by gabehollombe-aws** [comment]
Great! Thanks for sharing your steps to resolve the issue. If future folks run into this problem, I'm glad to know we'll have a fix documented here. 

Closing this issue.
