### ISSUE TITLE
Resource is not in the state stackUpdateComplete error.

### ISSUE THREAD

**Issue by iamenzoenzo** [aws-samples/amplify-photo-gallery-workshop#51]
Hi Gabe,

I'm getting this error now. I followed your instructions.

Resource is not in the state stackUpdateComplete
An error occurred during the push operation: Resource is not in the state stackUpdateComplete.

I got this after I entered amplify push. (the last step in this page https://amplify-workshop.go-aws.com/110_ai/20_prep_for_searching.html)

UPDATE_COMPLETE ConnectionStack AWS::CloudFormation::Stack Sat Nov 14 2020 07:43:37 GMT+0000 (Coordinated Universal Time) 
⠸ Updating resources in the cloud. This may take a few minutes...TypeError: events is not iterable
    at getUniqueStacksEvents (/home/ec2-user/.nvm/versions/node/v10.23.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js:506:28)
    at getStackEvents.then.stackEvents (/home/ec2-user/.nvm/versions/node/v10.23.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js:130:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:8711) UnhandledPromiseRejectionWarning: ExpiredToken: The security token included in the request is expired
    at Request.extractError (/home/ec2-user/.nvm/versions/node/v10.23.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/home/ec2-user/.nvm/versions/node/v10.23.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/ec2-user/.nvm/versions/node/v10.23.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/ec2-user/.nvm/versions/node/v10.23.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/home/ec2-user/.nvm/versions/node/v10.23.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/ec2-user/.nvm/versions/node/v10.23.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/ec2-user/.nvm/versions/node/v10.23.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/ec2-user/.nvm/versions/node/v10.23.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/ec2-user/.nvm/versions/node/v10.23.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/home/ec2-user/.nvm/versions/node/v10.23.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
(node:8711) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8711) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
⠇ Updating resources in the cloud. This may take a few minutes...TypeError: events is not iterable
    at getUniqueStacksEvents (/home/ec2-user/.nvm/versions/node/v10.23.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js:506:28)
    at getStackEvents.then.stackEvents (/home/ec2-user/.nvm/versions/node/v10.23.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js:130:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:8711) UnhandledPromiseRejectionWarning: ExpiredToken: The security token included in the request is expired
    at Request.extractError (/home/ec2-user/.nvm/versions/node/v10.23.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/home/ec2-user/.nvm/versions/node/v10.23.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/ec2-user/.nvm/versions/node/v10.23.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/ec2-user/.nvm/versions/node/v10.23.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/home/ec2-user/.nvm/versions/node/v10.23.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/ec2-user/.nvm/versions/node/v10.23.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/ec2-user/.nvm/versions/node/v10.23.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/ec2-user/.nvm/versions/node/v10.23.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/ec2-user/.nvm/versions/node/v10.23.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/home/ec2-user/.nvm/versions/node/v10.23.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
(node:8711) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
⠸ Updating resources in the cloud. This may take a few minutes...Error updating cloudformation stack
⠴ Updating resources in the cloud. This may take a few minutes...

**Comment by gabehollombe-aws** [comment]
I've seen this happen before at times when it takes longer than expected for the ElasticSearch cluster to provision. In your case, you reported seeing this error right after updating to include ElasticSearch, so I suspect this is what happened.

Try another `amplify push` and see if it works now?

**Comment by iamenzoenzo** [comment]
it worked after another amplify push. I was able to complete all the instructions. thanks Gabe!
